### ISSUE TITLE
Console spam: "TrackerReact engaged!"

### ISSUE THREAD

**Issue by Incisive** [ultimatejs/tracker-react#15]
Is this something that is going to remain in this library?  I'm not seeing it in the source code, however it's on the Atmosphere release of tracker-react.

**Comment by D1no** [comment]
Please update to the latest release.

**Comment by Incisive** [comment]
I'm using the latest atmosphere release which appears to be 1.0.2, anyone else able to reproduce this?  I'll try on a fresh meteor application later this afternoon.

**Comment by gabriel-dehan** [comment]
Not exactly the same issue here, but I can't install the 1.0.3 version I get a `no such version ultimatejs:tracker-react@1.0.3` when trying to force it, otherwise I just get the 1.0.2 version (with the profiler error)

Any clue as to why atmosphere is not delivering the right version ? I am using Meteor 1.3 beta.

**Comment by D1no** [comment]
Mh, maybe it has to do with the fact that I need to publish the package
while running meteor with appropriate release flag

maybe try this
meteor --release 1.3-beta.16 add ultimatejs:tracker-react@1.0.3

But I also don't see it anymore on atmosphere. I'll re-publish it soon.

Originally I wanted to wait for the release of Meteor 1.3 (due to some
commonJS hiccups) but I guess the rc just came out. So time to re-check
and finalize everything

**Comment by D1no** [comment]
TrackerReact has been re-published to version 1.0.4

**Comment by Incisive** [comment]
Great, thanks @D1no - Unfortunately I'll have to wait since I can't upgrade to RC1 since flow-router is broken at the moment.
