### ISSUE TITLE
subscription not updating

### ISSUE THREAD

**Issue by hoolymama** [ultimatejs/tracker-react#18]
Hi, 

Based on your example in the README, if I put a subscription in the constructor of a tracker react container, and that subscription depends on the user, then it is not updated when the user logs in or out. 

If I put it in the same method that fetches the records, then it works, but I have a strong feeling this is not the best way. How would you do this?

I posted the question more fully [on StackOverflow.](http://stackoverflow.com/questions/36271297/where-should-i-put-the-meteor-subscription-in-a-tracker-react-container)

Many thanks!

**Comment by D1no** [comment]
Hey, yes, that is because it is in the constructor, which is run once before the component is mounted. If you want to have a subscription that is reactive _while the component is rendered_, it needs to be in the render block.

``` js
render() {
   Meteor.subscribe("tasks", Meteor.userId() )
   //... displays the tasks
   return (
      // some jsx
   )
  }
```

 A similar question was asked here: https://github.com/D1no/TrackerReact-Example/issues/5#issue-137732932

**Comment by hoolymama** [comment]
Thank you!

**Comment by hoolymama** [comment]
Hey, would you like to paste your reply into the [stackoverflow question](http://stackoverflow.com/questions/36271297/where-should-i-put-the-meteor-subscription-in-a-tracker-react-container) and I will mark it accepted.
