### ISSUE TITLE
this.autorun

### ISSUE THREAD

**Issue by maxnowack** [ultimatejs/tracker-react#21]
I really like the usage of `this.autorun` in blaze. I've already build this functionality for react and could create a pull request.
But I'm not sure if `this.autorun` should be in the scope of this package. What do you think?

**Comment by D1no** [comment]
Mh, I don't think I understand what you try to do. You can simply use Tracker.autorun ? TrackerReact is simply for facilitating the use of reactive resources inside of the render method.

**Comment by maxnowack** [comment]
`this.autorun` in Blaze is a `Tracker.autorun` that stops the computation if the template will be destroyed.  
In Blaze I often use `this.subscribe` inside of a `this.autorun` (in a `onCreated` hook), if I need a template level subscription with a reactive dependency.
Sometimes I need the same in react. But I don't want to put the `Meteor.subscribe` inside of the `render` method, since the component will be rerendered every time the dependency for the subscription change.

**Comment by D1no** [comment]
When the component is unmounted, the autorun will be already stopped. If you want to unsuscripe when a component is unmount, simply put it into `componentWillUnmount` method. TrackerReact does not magically manage your subscriptions - that's the applications / your job. Also, the render method is not what you think it is in react. It runs all the time and it is perfectly reasonable to have reactive subscriptions inside of the render method. Because in the react world, the render method is better understood as the "rendered" or "mounted" method. The only method that is alive during the life cycle of a component. Please read up on react.
