### ISSUE TITLE
Does TrackerReact force components to update when data changes ? 

### ISSUE THREAD

**Issue by furkanedu** [ultimatejs/tracker-react#23]
```
import React,{Component} from 'react';
import TrackerReact from 'meteor/ultimatejs:tracker-react';
import {Lists} from '../lib/collections/lists.js';

export default class App extends TrackerReact(Component) {
    constructor(){
        super();
        // this.state = {lists : this.lists()}
    }
    lists(){
        return Lists.find().fetch();
    }
    addList(e){
        e.preventDefault();
        //let text = this.refs.list.value ;
        let text = this._inputList.value ;
        console.log(this._inputList.value);
        Lists.insert({
            title : text
        });
        this._inputList.value = "";

        //this.setState({lists : this.lists()});
    }
    render() {
        return (
            <div>
                <h2>Lists</h2>
                <ul>
                    {this.lists().map((a,b)=>(
                        <List key={a._id} title={a.title} /> 
                    ))} 
                </ul>
                <form onSubmit={this.addList.bind(this)}>
                    <input 
                        type="text"
                        ref={(input)=>{
                            this._inputList =  input ;
                        }}
                        placeholder="add list bro"
                    />
                </form>
            </div>
        )
    }  
}
```

Although I didn t use states, component updates itself. I wonder why ? I thought I would have to assign lists to state and change state on method call. But it seems TrackerReact already updates the component. How should I approach this issue ?

**Comment by D1no** [comment]
Please keep in mind, that the render method in react is not what you think it is. In fact, the render method runs all the time and should better have been called "rendered" instead of "render". Since it runs all the time, the overhead of an reactive render method is marginal because the work comes in the form of (efficient) diffing and batching algorithms if real changes are detected. In react, you can call render as often as you want - only check if you make real changes to often than you should. I will close future issues of this kind, if no real benchmarking is attached to it. Please read up on the way react works.

**Comment by furkanedu** [comment]
Thanks for your enlightening answer.
