### ISSUE TITLE
Composition implementation doesn't work but Mixin works perfectly

### ISSUE THREAD

**Issue by mattmacpherson** [ultimatejs/tracker-react#26]
I'm on Meteor 1.4.2 and can't figure out why the composition implementation won't work with my app but the mixin example works perfectly. What are some variables that would cause this behaviour?

**Comment by steinitz-zz** [comment]
I confirm that this is an issue.

I got it working after some struggle.  Note that I moved the code out of the package into project files since WebStorm 2016.2.4 doesn't seem to like to breakpoint packages.

Anyway, the key fix is changing line 62 of main.js from:

`this.render = () => {
`

to:
`this.constructor.prototype.render = () => {
`

I also added these lines to the constructor just in case:

```
    this.autorunRender = this.autorunRender.bind(this);
    this.autorunOnce = this.autorunOnce.bind(this);
```

There may be other issues which I've forgotten that I fixed.

Anyway, I hope this is helpful.
